[package]
authors.workspace      = true
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "bench-transaction"
publish                = false
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[[bench]]
harness = false
name    = "time_counting_benchmarks"
path    = "src/time_counting_benchmarks/prove.rs"

[dependencies]
# Workspace dependencies
miden-lib     = { workspace = true }
miden-objects = { features = ["testing"], workspace = true }
miden-testing = { workspace = true }
miden-tx      = { workspace = true }

# Miden dependencies
miden-processor = { workspace = true }

# External dependencies
anyhow      = { workspace = true }
rand_chacha = { default-features = false, version = "0.9" }
serde       = { features = ["derive"], version = "1.0" }
serde_json  = { features = ["preserve_order"], package = "serde_json", version = "1.0" }

[dev-dependencies]
criterion = { features = ["html_reports"], version = "0.6" }
